# Creating Arrays

In [2]:
#concevntion 
import numpy as np
#creating 1d array
n1 = np.array([3,4,5,6])
print(n1)

[3 4 5 6]


In [3]:
#creating 2d array
n2 = np.array([[3,5,6,7],[4,5,6,7]])
print(n2)

[[3 5 6 7]
 [4 5 6 7]]


In [4]:
#zero filled 2d array
n3 = np.zeros([3,5],dtype='int32')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
#array filled with ones
n4 = np.ones([2,3,3],dtype='int32')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [3]:
#empty array - contain random junk values
n5 = np.empty([2,3])
print(n5)

[[7.27370851e+223 5.48302998e-096 3.12237215e-120]
 [5.38206251e+228 1.04990772e-153 9.05437256e+271]]


In [7]:
#create array with range of values
n6 = np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
n7 = np.arange(-5,30,5) #start,stop,step
print(n7)

[-5  0  5 10 15 20 25]


In [4]:
#linearly spaced entries
n8 = np.linspace(0,20,num=8,dtype = 'int')
print(n8)

[ 0  2  5  8 11 14 17 20]


In [10]:
n9 = np.full([2,5],99) #create by specifying dimension and fill with values
print(n9)

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [11]:
n5.fill(9) #fill an array with values
print(n5)

[[9. 9. 9.]]


# Accessing

In [ ]:
n1 = np.array([3,4,5,6])

In [12]:
print(n1[0])

3


In [13]:
print(n1[-1])

6


In [7]:
n2 = np.array([[3,5,6,7],[4,5,6,7]])
print(n2)

[[3 5 6 7]
 [4 5 6 7]]


In [14]:
print(n2[1,0])

4


In [15]:
print(n2[1,:])

[4 5 6 7]


In [8]:
print(n2[:,2])

[6 6]


In [15]:
n4 = np.ones([2,3,3],dtype='int32')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [16]:
n4[1,0,2] = 10
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1 10]
  [ 1  1  1]
  [ 1  1  1]]]


# Size and Shape

In [18]:
print(n4.ndim) #ndim gives number of dimensions or axes

3


In [19]:
print(n4.shape)

(2, 3, 3)


In [20]:
print(n4.size)

18


In [21]:
print(n4.dtype)

int32


# Reshaping and Array Conversions

In [28]:
n12 = n10.reshape(2,4)
print(n12)

[[ 3  4  1  9]
 [ 5 10  8  7]]


In [29]:
#Joining 2 arrays using concatenate
n13 = np.arange(4)
print(n13)
n14 = np.arange(5,9)
print(n14)
n15 = np.concatenate((n13,n14))
print(n15)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


# Indexing and slicing

In [37]:
print(n21[3:7])

[  3   4   5 100]


# Math

In [67]:
print(n22)
print(n23)
print(n22+n23)
print(n23*n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[25 36]
 [49 64]]


In [85]:
print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*10)

[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
489
200
2
[1000 2000   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190]


In [86]:
print(np.cos(n26))

[ 0.86231887  0.48718768 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


# Random Numbers

In [79]:
np.random.rand(3,3)

array([[0.6756754 , 0.58657492, 0.42845491],
       [0.48703211, 0.25432168, 0.89789337],
       [0.65050801, 0.58615413, 0.57901873]])

In [83]:
np.random.randint(100,size=(4,2))

array([[65, 82],
       [89, 38],
       [39, 56],
       [98, 76]])